# Generated by Django 5.2.11 on 2026-02-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='pdf',
            new_name='file',
        ),
    ]
